# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'drink',
            },
        ),
        migrations.CreateModel(
            name='Ordereddrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('drinkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAutomatedCafe.Drink')),
            ],
            options={
                'db_table': 'ordereddrink',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertime', models.DateTimeField(db_column='orderTime')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAutomatedCafe.Client')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountpaid', models.FloatField(db_column='amountPaid')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAutomatedCafe.Client')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codebar', models.IntegerField()),
            ],
            options={
                'db_table': 'tables',
            },
        ),
        migrations.AddField(
            model_name='ordereddrink',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAutomatedCafe.Orders'),
        ),
        migrations.AddField(
            model_name='client',
            name='tableid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheAutomatedCafe.Tables'),
        ),
        migrations.AlterUniqueTogether(
            name='ordereddrink',
            unique_together=set([('orderid', 'drinkid')]),
        ),
    ]
